//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaNamjestaja_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dobavljaci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dobavljaci()
        {
            this.Ulazi = new HashSet<Ulazi>();
        }
    
        public int DobavljacID { get; set; }
        public string Naziv { get; set; }
        public string KontaktOsoba { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public string Adresa { get; set; }
        public string Web { get; set; }
        public bool Statusa { get; set; }
        public string ZiroRacun { get; set; }
        public string Napomena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ulazi> Ulazi { get; set; }
    }
}
