//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaNamjestaja_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvodi()
        {
            this.IzlaziStavke = new HashSet<IzlaziStavke>();
            this.NarudzbaStavke = new HashSet<NarudzbaStavke>();
            this.Ocjene = new HashSet<Ocjene>();
            this.SkladistaProizvod = new HashSet<SkladistaProizvod>();
            this.UlaziStavke = new HashSet<UlaziStavke>();
        }
    
        public int ProizvodID { get; set; }
        public decimal Cijena { get; set; }
        public string Naziv { get; set; }
        public string Sifra { get; set; }
        public bool Statuss { get; set; }
        public int VrstaProizvoda { get; set; }
        public byte[] SlikaThumb { get; set; }
        public byte[] Slika { get; set; }
        public int TipID { get; set; }
        public int ModelID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzlaziStavke> IzlaziStavke { get; set; }
        public virtual ModelProizvoda ModelProizvoda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NarudzbaStavke> NarudzbaStavke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocjene> Ocjene { get; set; }
        public virtual TipProizvoda TipProizvoda { get; set; }
        public virtual VrsteProizvoda VrsteProizvoda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkladistaProizvod> SkladistaProizvod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UlaziStavke> UlaziStavke { get; set; }
    }
}
