//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaNamjestaja_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkladistaProizvod
    {
        public int SkladisteProizvodID { get; set; }
        public int Kolicina { get; set; }
        public int SkladisteID { get; set; }
        public int ProizvodID { get; set; }
    
        public virtual Skladista Skladista { get; set; }
        public virtual Proizvodi Proizvodi { get; set; }
    }
}
