//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaNamjestaja_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_TopSellingProducts
    {
        public string Sifra { get; set; }
        public string Naziv { get; set; }
        public string Vrsta { get; set; }
        public string Tip { get; set; }
        public string Model { get; set; }
        public decimal Cijena { get; set; }
        public Nullable<int> Prodato { get; set; }
    }
}
