//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaNamjestaja_UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eProdajaNamjestaja_UI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite adresu.
        /// </summary>
        internal static string adresa_req {
            get {
                return ResourceManager.GetString("adresa_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa mora imati najmanje 3 karaktera!.
        /// </summary>
        internal static string adresa_req_length {
            get {
                return ResourceManager.GetString("adresa_req_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite cijenu.
        /// </summary>
        internal static string cijena_req {
            get {
                return ResourceManager.GetString("cijena_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobavljač sa unešenim nazivom već postoji!.
        /// </summary>
        internal static string dobavljac_exists {
            get {
                return ResourceManager.GetString("dobavljac_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail već postoji!.
        /// </summary>
        internal static string dobavljac_mail_exists {
            get {
                return ResourceManager.GetString("dobavljac_mail_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjesno ste sačuvali podatke o dobavljaču!.
        /// </summary>
        internal static string dobavljac_succ {
            get {
                return ResourceManager.GetString("dobavljac_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žiro račun već postoji!.
        /// </summary>
        internal static string dobavljac_zracun_exists {
            get {
                return ResourceManager.GetString("dobavljac_zracun_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite faks.
        /// </summary>
        internal static string faks_req {
            get {
                return ResourceManager.GetString("faks_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faks treba da sadrži najmanje 3 karatera!.
        /// </summary>
        internal static string faks_req_length {
            get {
                return ResourceManager.GetString("faks_req_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite broj faktuure.
        /// </summary>
        internal static string faktura_error {
            get {
                return ResourceManager.GetString("faktura_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faks mora imati 6 cifara.
        /// </summary>
        internal static string fax_req_length {
            get {
                return ResourceManager.GetString("fax_req_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite ime.
        /// </summary>
        internal static string fname_req {
            get {
                return ResourceManager.GetString("fname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime treba da sadrzi najmanje 3 karaktera!.
        /// </summary>
        internal static string fname_req_length {
            get {
                return ResourceManager.GetString("fname_req_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite grad.
        /// </summary>
        internal static string grad_req {
            get {
                return ResourceManager.GetString("grad_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite kolicinu.
        /// </summary>
        internal static string Kolicina_error {
            get {
                return ResourceManager.GetString("Kolicina_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite kontakt.
        /// </summary>
        internal static string kontakt_req {
            get {
                return ResourceManager.GetString("kontakt_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt treba da sadrži najmanje 3 karaktera!.
        /// </summary>
        internal static string kontakt_req_lenth {
            get {
                return ResourceManager.GetString("kontakt_req_lenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci su uspješno sačuvani.
        /// </summary>
        internal static string korisnik_succ {
            get {
                return ResourceManager.GetString("korisnik_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite prezime.
        /// </summary>
        internal static string lname_req {
            get {
                return ResourceManager.GetString("lname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime treba da sadrzi najmanje 3 karaktera!.
        /// </summary>
        internal static string lname_req_length {
            get {
                return ResourceManager.GetString("lname_req_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesena lozinka nije validna!.
        /// </summary>
        internal static string login_pass_error {
            get {
                return ResourceManager.GetString("login_pass_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik sa datim korisničkim imenom ne postoji.
        /// </summary>
        internal static string login_username_err {
            get {
                return ResourceManager.GetString("login_username_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unijeli ste pogrešan format e-mail adrese.
        /// </summary>
        internal static string mail_error {
            get {
                return ResourceManager.GetString("mail_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite mail.
        /// </summary>
        internal static string mail_req {
            get {
                return ResourceManager.GetString("mail_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite mail.
        /// </summary>
        internal static string mail1_req {
            get {
                return ResourceManager.GetString("mail1_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite model proizvoda.
        /// </summary>
        internal static string model_req {
            get {
                return ResourceManager.GetString("model_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite napomenu.
        /// </summary>
        internal static string napomena_error {
            get {
                return ResourceManager.GetString("napomena_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv već postoji.
        /// </summary>
        internal static string naziv_exists {
            get {
                return ResourceManager.GetString("naziv_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv je obavezno polje.
        /// </summary>
        internal static string naziv_req {
            get {
                return ResourceManager.GetString("naziv_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv treba da sadrzi najmanje 3 karaktera!.
        /// </summary>
        internal static string naziv_req_lenth {
            get {
                return ResourceManager.GetString("naziv_req_lenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite naziv dobavljaca.
        /// </summary>
        internal static string nazivDobavljaca_req {
            get {
                return ResourceManager.GetString("nazivDobavljaca_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste otkazali narudžbu!.
        /// </summary>
        internal static string order_cancel {
            get {
                return ResourceManager.GetString("order_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste procesirali narudžbu.
        /// </summary>
        internal static string order_succ {
            get {
                return ResourceManager.GetString("order_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite lozinku.
        /// </summary>
        internal static string pass_req {
            get {
                return ResourceManager.GetString("pass_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka treba da sadrzi najmanje 3 karaktera!.
        /// </summary>
        internal static string pass_req_length {
            get {
                return ResourceManager.GetString("pass_req_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite telefon.
        /// </summary>
        internal static string phone_req {
            get {
                return ResourceManager.GetString("phone_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon mora imati 6 cifara.
        /// </summary>
        internal static string phone_req_length {
            get {
                return ResourceManager.GetString("phone_req_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika nije odgovarajućih dimenzija. Odaberite drugu!.
        /// </summary>
        internal static string picture_size_war {
            get {
                return ResourceManager.GetString("picture_size_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da odaberete sliku dimenzija većih od.
        /// </summary>
        internal static string picture_war {
            get {
                return ResourceManager.GetString("picture_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjesno ste dodali podatke o novom proizvodu!.
        /// </summary>
        internal static string product_add_succ {
            get {
                return ResourceManager.GetString("product_add_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke o proizvodu!.
        /// </summary>
        internal static string product_edit_succ {
            get {
                return ResourceManager.GetString("product_edit_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite ulogu.
        /// </summary>
        internal static string roles_req {
            get {
                return ResourceManager.GetString("roles_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite sifru.
        /// </summary>
        internal static string sifra_error {
            get {
                return ResourceManager.GetString("sifra_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra vec postoji.
        /// </summary>
        internal static string sifra_exists {
            get {
                return ResourceManager.GetString("sifra_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra mora imati najmanje 7 karaktera!.
        /// </summary>
        internal static string sifra_length {
            get {
                return ResourceManager.GetString("sifra_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite sifru.
        /// </summary>
        internal static string sifra_req {
            get {
                return ResourceManager.GetString("sifra_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skladište već postoji!.
        /// </summary>
        internal static string skladiste_exists {
            get {
                return ResourceManager.GetString("skladiste_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjesno ste evidentirali podatke o novom skladistu!.
        /// </summary>
        internal static string skladiste_succ {
            get {
                return ResourceManager.GetString("skladiste_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite sliku.
        /// </summary>
        internal static string slika_req {
            get {
                return ResourceManager.GetString("slika_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite spol.
        /// </summary>
        internal static string spol_req {
            get {
                return ResourceManager.GetString("spol_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite telefon.
        /// </summary>
        internal static string telefon_req {
            get {
                return ResourceManager.GetString("telefon_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite tip proizvoda.
        /// </summary>
        internal static string tip_req {
            get {
                return ResourceManager.GetString("tip_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulazi nisu uneseni.
        /// </summary>
        internal static string ulazi_error {
            get {
                return ResourceManager.GetString("ulazi_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite korisničko ime.
        /// </summary>
        internal static string username_req {
            get {
                return ResourceManager.GetString("username_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko ime treba da sadrzi najmanje 3 karaktera!.
        /// </summary>
        internal static string username_req_length {
            get {
                return ResourceManager.GetString("username_req_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite vrstu proizvoda.
        /// </summary>
        internal static string vrsta_req {
            get {
                return ResourceManager.GetString("vrsta_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite web.
        /// </summary>
        internal static string web_req {
            get {
                return ResourceManager.GetString("web_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite ziro racun.
        /// </summary>
        internal static string ziroRac_req {
            get {
                return ResourceManager.GetString("ziroRac_req", resourceCulture);
            }
        }
    }
}
